<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <artifactId>employee-back-web-digitaldocument-bucket-client</artifactId>
  <packaging>jar</packaging>
  <name>employee-back-web-digitaldocument-bucket-client</name>

  <parent>
    <groupId>com.mercadona.employee.digitaldocument</groupId>
    <artifactId>employee-back-web-digitaldocument</artifactId>
    <version>1.0.0</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>

  <dependencies>

    <dependency>
      <groupId>com.mercadona.employee.digitaldocument</groupId>
      <artifactId>employee-back-web-digitaldocument-application</artifactId>
    </dependency>

    <dependency>
      <groupId>com.mercadona.framework.cna</groupId>
      <artifactId>fwkcna-starter-buckets</artifactId>
    </dependency>

  </dependencies>

</project>
