metadata:
  labels:
    app: examples
    description: Examples Controller
    title: Quickstart service demo
spec:
  deploy:
    apiFileName: examples-openapi-v3.yaml
    type:
      fwkSpringBoot:
        groupId: com.mercadona.employee.web-digitaldocument
        artifactId: examples-api
        package: com.mercadona.employee.api.web-digitaldocument
        interfacesWithTags: false
