spring:
  flyway:
    enabled: true
    locations: classpath:migration/versions

  datasource:
    url: jdbc:postgresql://localhost:5433/prueba
    username: sa
    password: root
    driver-class-name: org.postgresql.Driver

  kafka:
    properties:
      schema.registry.url: http://localhost:8085
      security:
        protocol: "PLAINTEXT"
    consumer:
      bootstrap-servers: localhost:29092
      properties:
        key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

clients:
  cardgenerator:
    base-path: http://localhost:8081

fwkcna:
  security:
    enabled: false
  buckets:
    - id: digital-documents
      bucket-name: digital-documents
      enabled: true
      url: http://localhost:9000
      provider: minio
      credentials:
        access-key: minioadmin
        secret-key: minioadmin
