spring:
  application:
    name: employee-back-web-digitaldocument
  kafka:
    consumer:
      properties:
        key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

fwkcna:
  kafka:
    enabled: true
    consumer:
      topics:
        groups:
          employee:
            main: thirdparty.employee.employee.event.public.v0.table.cpd
            group-id: thirdparty_employee_employee_employee_back_digital_document
  buckets:
    - id: digital-documents
      bucket-name: ${BUCKET_NAME:digital-documents}
      enabled: true
      url: ${BUCKET_ENDPOINT}   # TODO: set per environment
      provider: gcs             # TODO: change to netapp if needed
      credentials:
        access-key: ${BUCKET_ACCESS_KEY}
        secret-key: ${BUCKET_SECRET_KEY}

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: [ info, health, metrics, prometheus ]

server:
  port: 8080

clients:
  cardgenerator:
    base-path: # TODO: set per environment (e.g. https://cardgenerator.srv.mercadona.com)
