spring:
  application:
    name: employee-back-web-digitaldocument
  kafka:
    consumer:
      properties:
        key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

fwkcna:
  kafka:
    enabled: true
    consumer:
      topics:
        groups:
          employee:
            main: employee
            group-id: employee-digital-document-consumer-group

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: [ info, health, metrics, prometheus ]


server:
  port: 8080
